name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh
      shell: bash